// src/lib/companyDomains.ts
export const COMPANY_DOMAINS: Record<string, string> = {
    // --- Greenhouse ---
    stripe: 'stripe.com',
    airbnb: 'airbnb.com',
    doordash: 'doordash.com',
    coinbase: 'coinbase.com',
    cloudflare: 'cloudflare.com',
    datadog: 'datadoghq.com',
    dropbox: 'dropbox.com',
    figma: 'figma.com',
    robinhood: 'robinhood.com',
    reddit: 'reddit.com',
    hubspot: 'hubspot.com',
    asana: 'asana.com',
    affirm: 'affirm.com',
    lyft: 'lyft.com',
    brex: 'brex.com',
    twilio: 'twilio.com',
    gusto: 'gusto.com',
    discord: 'discord.com',
    instacart: 'instacart.com',
    segment: 'segment.com',
    postman: 'postman.com',
    databricks: 'databricks.com',
    peloton: 'onepeloton.com',
    coursera: 'coursera.org',
    maven: 'maven.com',
    pilot: 'pilot.com',
    mercury: 'mercury.com',
};
