// src/lib/companyDomains.ts
export const COMPANY_DOMAINS: Record<string, string> = {
    // --- Greenhouse ---
    stripe: 'stripe.com',
    airbnb: 'airbnb.com',
    doordash: 'doordash.com',
    coinbase: 'coinbase.com',
    cloudflare: 'cloudflare.com',
    datadog: 'datadoghq.com',
    servicenow: 'servicenow.com',
    shopify: 'shopify.com',
    openai: 'openai.com',
    dropbox: 'dropbox.com',
    figma: 'figma.com',
    plaid: 'plaid.com',
    robinhood: 'robinhood.com',
    reddit: 'reddit.com',
    hubspot: 'hubspot.com',
    asana: 'asana.com',
    affirm: 'affirm.com',
    lyft: 'lyft.com',
    brex: 'brex.com',
    twilio: 'twilio.com',
    gusto: 'gusto.com',
    discord: 'discord.com',
    instacart: 'instacart.com',
    ramp: 'ramp.com',
    segment: 'segment.com',
    notion: 'notion.so',
    postman: 'postman.com',
    databricks: 'databricks.com',
    zapier: 'zapier.com',
    attentive: 'attentivemobile.com',
    peloton: 'onepeloton.com',
    coursera: 'coursera.org',
    maven: 'maven.com',
    pilot: 'pilot.com',
    mercury: 'mercury.com',

    // --- Lever ---
    netflix: 'netflix.com',
    nvidia: 'nvidia.com',
    snowflake: 'snowflake.com',
    zoom: 'zoom.us',
    slack: 'slack.com',
    quora: 'quora.com',
    yelp: 'yelp.com',
    paypal: 'paypal.com',
    lever: 'lever.co',
    square: 'squareup.com',
    'shopify-lever': 'shopify.com',
    sonos: 'sonos.com',
    medium: 'medium.com',
    unity: 'unity.com',
    hashicorp: 'hashicorp.com',
    docker: 'docker.com',
    duolingo: 'duolingo.com',
    flexport: 'flexport.com',

    // --- Top Tech (manual list) ---
    google: 'google.com',
    apple: 'apple.com',
    microsoft: 'microsoft.com',
    amazon: 'amazon.com',
    meta: 'meta.com',
    salesforce: 'salesforce.com',
    adobe: 'adobe.com',
    oracle: 'oracle.com',
    uber: 'uber.com',
};
